---
title: "Bioeconomy Accounting: Methods and Pilot Application to 13 Latin American Economies"
authors:
  - name: Renato Vargas
    affiliation:
      - ref: chw
    email: renovargas@gmail.com
    roles: writing
    corresponding: true
  - name: Andrés Mondaini
    affiliation: 
      - ref: eclac
    email: andres.mondaini@cepal.org
  - name: Adrián Rodríguez
    email: adrian.rodriguez@cepal.org
    affiliation: 
      - ref: eclac
  - name: Mónica Rodríguez
    email: RODRIGUEZZM@bccr.fi.cr
    affiliation: 
      - ref: bccr
  - name: Irene Alvarado
    email: ALVARADOQI@bccr.fi.cr
    affiliation: 
      - ref: bccr
  
  # - name: Luis Fernando Sánchez
  #   email: SANCHEZSL@bccr.fi.cr
  #   affiliation: 
  #     - ref: bccr
affiliations:
  - id: chw
    name: CHW, S.A.
  - id: eclac
    name: Economic Commission for 
          Latin America and The Caribbean
  - id: bccr
    name: Banco Central de Costa Rica
abstract: |
  We propose a practical methodology to estimate Bioeconomic Satellite 
  Accounts following the rules outlined in the System of National Accounts 
  for analytical extensions. 
  This methodology reaggregates classifications 
  within the Supply and Use tables of this system 
  to highlight the economic contribution of inputs and outputs driven by 
  biological resources for all economic activities. 
  In contrast to similar studies, we suggest that an _a priori_ 
  classification of economic activities as either "bioeconomic" or 
  "non-bioeconomic" underestimates value added by biological resources 
  that fall outside the predetermined activities. 
  Instead, we assess the economic contribution driven by biological 
  resources for all activities and propose direct and indirect methods 
  to rank them according to their importance for bioeconomic policy. 
  We exemplify the methodology with the case of Costa Rica and 
  provide estimates for 13 Latin American economies.
  
bibliography: references.bib
csl: apa-6th-edition.csl
---

## Introduction

In 2018, the Costa Rican Government published that country's National Bioeconomy Strategy, following closely an internationally agreed definition crafted in the context of the German Bioeconomy Council [@german_bioeconomy_council_global_2018], which states that the Bioeconomy is:

> "The production, use, conservation, and regeneration of biological resources, including the knowledge, science, technology, and innovation related to these resources, to provide information, products, processes, and services to all economic sectors, with the goal of advancing toward a sustainable economy [@gobiernodecostarica2020]."

Additionally, this strategy defines "biological resources" within the framework as **i)** biomass cultivated to produce food, fodder, fibers, and energy; **ii)** biomass from marine resources and that produced through aquaculture; **iii)** forest biomass, especially that cultivated for use in the forestry and paper industries, as well as that legally extracted from natural ecosystems; **iv)** residual biomass from the agricultural, fishing and aquaculture, forestry, and agro-industrial sectors; **v)** biomass that can be recovered from urban waste; **vi)** liquid waste from livestock and human activities; and **vii)** terrestrial and marine biodiversity, including the biodiversity of inland waters.

Public policies informed by data have been shown to be more efficient in reaching their objectives and, while Costa Rica has a long tradition in the production of environmental accounts [@bccr_cuentas_2021] following the System of Environmental and Economic Accounts–SEEA–[@europeancommission2013], there was a gap in the assessment of the direct and indirect contribution of biological resources to the economy that policymakers needed to close.

Given the richness of information regarding biological resources that is collected to assess the economic performance of the country, we saw an opportunity to close this gap by extending the System of National Accounts (SNA), the framework with which Gross Domestic Product (GDP) is measured, among many other indicators, to highlight the contribution of those resources. The SNA manual [@europeancommission2009, p. 523] provides clear guidelines on how to develop analytical extensions–specifically *Key Sector Accounts* and *Satellite Accounts*–and we chose to adhere to those guidelines to avoid deviations from SNA's concepts and accounting rules and mantain comparability with traditional economic indicators. In particular, we focused on reaggregating classifications of the Supply and Use Tables that detail the production account of the System.

This strict adherence to the principles of SNA and the standarization procedure developed to handle Supply and Use data in the case of Costa Rica, allowed us to readily extend this exercise to 13 Latin American economies. This was possible because these economies have made their Supply and Use tables publicly available and this information has been centralized in a repository [@eclac2021]. Relying on the SNA principles, definitions, classifications, and accounting rules also gave us an opportunity to express results related to the Bioeconomy using concepts that are easily understood by policy-makers because of their widespread use in economic performance communications and analysis.

## Data and Methods

### Supply and Use Tables are used as data sources

The main source of information for Bioeconomy Satellite Accounts are Supply and Use tables from SNA [@europeancommission2009a], which are multi-dimensional matrices that show in great detail the production and import of goods and services by economic activities in a country and how those are used, either in the production process itself as inputs, by other agents in the economy, or by the rest of the world. The detail of products is arranged according to the Central Product Classification–CPC–[@unitednations2015] and economic activities are arranged according to the International Standard Industrial Classification of All Economic Activities–ISIC–[@unitednations2008] or local adaptations of both of them. In addition to products and economic activities, these tables have an additional dimension that shows different types of transactions that those products drive in their journey from producers to consumers.

In the case of the supply table, the sequence of those transactions describes a flow where different products in the rows are produced by economic activities in the columns at basic prices (i.e., the price at the farm gate, factory, or commercial establishment). This output is then combined with imports free of insurance and freight costs to form the supply at basic prices. However, this is not the price paid by economic agents. In its way to market, taxes on products are added to the basic price supply, minus any subsidies received, followed by distribution margins (transportation and trade costs). This results in the total supply at purchaser's or market prices, found in the last column of the table, which represents what is available for purchase by the same economic agents in the use table. For these additional columns of transactions, the product detail (rows) is mantained, but not the economic activity detail.

The Use Table shows how the supply from the last column of the Supply Table is purchased by economic agents for various purposes at market prices, expressed in the form of different transactions. Similar to the production above, this table shows Intermediate Consumption, which refers to the purchase of inputs by economic activities used to produce the goods and services in the first table (essentially, the production recipe for each economic activity). The portion of the supply that does not become an input in the production process remains available on the market for other domestic and foreign economic agents. The other transactions in the remaining columns illustrate that these goods and services can be exported; consumed by households, nonprofit institutions serving households (NPISH), and the general government; or they can be used as durable goods in gross capital formation; moved in or out of storage to be consumed in a different accounting period (changes in inventories); or get sold as valuable items. It is important to note that, row by row (product detail), the Total Use column equals the last column of the Supply Table, adhering to the economic principle of equality between supply and demand.

In a first step, our methodology contrasts the different products from the CPC classification against the definition of the Bioeconomy shown in the introductory paragraphs [@gobiernodecostarica2020a; @germanbioeconomycouncil2018], in general, and that of biological resources in particular, and we decide whether the product matches any of the elements of the

### A deviation from other studies

To uncover the contribution of biological inputs to the Economy, we propose a deviation from the existing efforts in the field; hereafter, "the traditional approach". These first exercises have deemed certain economic activities as "bioeconomic," based on their primary production, and they have added together, either all, or a fraction of their Value Added (VA) as a proxy for the "Bioeconomic GDP". This has been a necessary compromise, because "biological" is a quality of products, but VA and GDP are aggregates that are estimated at the economic activity or total economy level, not from the product perspective. While these first approximations have provided valuable estimates of the size of the Bioeconomy, they have limitations.

Within the production account of the System of National Accounts, often summarized into Supply and Use Tables (SUTs), economic activities can produce more than one product and, in turn, any product in the Economy can be produced by more than one activity. Activities will normally have a larger fraction of their output devoted to a group of products that share characteristics, which is deemed their primary production, and it will be used to determine the corresponding economic activity classification name. For example, all the production of companies that grow strawberries, cranberries, and blackberries, almonds, cashew nuts, and chestnuts, will be recorded under sector "0125 - Growing of other tree and bush fruits and nuts" of the International Standard Industry Classification (ISIC), Revision 4, at four digits. Some activities will also have a smaller fraction of their production that corresponds to the primary production of another sector. For example, it could be common in a certain region for some berries farms to directly sell small batches of fermented drinks that, which would normally be classified as primary production of another activity: "1102 - Manufacture of wines", but that probably do not go through a formal industrial process.

## Data

## Results

## Discussion

## References
